### ISSUE TITLE
Issues with JDK9

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#452]
There are quite a few problems that appeared on JDK 9.

One of them was mentioned by @Abu-Abdullah on Gitter:
```
[AWT-EventQueue-0] ERROR com.alee.utils.ProprietaryUtils - java.lang.NoSuchFieldException: Field "AA_TEXT_PROPERTY_KEY" not found in class: sun.swing.SwingUtilities2
java.lang.NoSuchFieldException: Field "AA_TEXT_PROPERTY_KEY" not found in class: sun.swing.SwingUtilities2
```
It seems that there were major changes to the internal text rendering made in JDK 9 and the field requested above doesn't exist anymore. To be even more precise - `AATextInfo` class doesn't exist anymore and was replaced by common `Graphics2D` settings.

There are also some other issues which can be seen in runtime on the lists related to reflection API usage.

**Comment by link0802** [comment]
I believe It happened due to changes made in JDK 9. Something like https://github.com/mgarin/weblaf/issues/452. Unfortunately, currently, I haven't access to my Linux laptop to test it and make pull request  :(

**Comment by mgarin** [comment]
Just a short update - I will be patching known JDK 9 -related issues somewhere around the middle of the next week. Fixes will only be going into the `styling` branch and all related builds.

Although I still do not recommend running WebLaF under JDK 9 ea builds as there might be more issues hidden from sight as I haven't properly tested it yet.

**Comment by mgarin** [comment]
I have fixed a few issues that have been appearing under JDK 9 and 10. I have also updated the mechanism that detects JDK version to be properly able to run version-related code and patched some of that version-related code to work under JDK 9+.

These changes have been added with 57ab5dd7ba3c8085fc18c456428bb7823ef95146 commit in `styling` branch and new snapshot builds will soon be available.

**Comment by mokun** [comment]
When I use the 1.2.9-snapshot version, The "AA_TEXT_PROPERTY_KEY" exception is gone. But I still have issues with xstream v1.4.9 used by weblaf.

See this [issue](https://github.com/x-stream/xstream/issues/101)

**Comment by mgarin** [comment]
There is, unfortunately, no way to avoid those warnings anyhow right now. I've already investigated this problem when I was trying to fix all JDK9+ issues.

Basically you get those warnings because some part of your code (or any library you use) is doing some "illegal" Reflection operations. Like accessing a private field, changing a final field value, calling private methods or constructors etc. Those operations can now be allowed only if you have configured your module permissions in a specific way. 

Obviously default JDK modules are NOT configured to allow anyone to access such stuff. Which basically means that, for instance, any Swing framework classes can only be used through the public API which is quite bad for many cases.

XStream does take a big part in WebLaF's Reflection usage, but it is also used within the library for other things. A lot actually. Its main use is still configuring components and UIs, but quite a few "illegal" things are also done to go around Swing limitations and some badly designed APIs. There are also quite a few Reflection usages that help supporting various features on different JDK versions without directly touching proprietary APIs. 

There is only one approach that would allow you to avoid these warnings on JDK9+ but it is rather inconvenient. You can use `--add-opens` and `--add-exports` command line options for JVM to allow accessing modules that do not provide the rights you need by default. 

There are quite a few articles around the internet explaining how those options work, for example:
https://blog.codefx.org/java/five-command-line-options-to-hack-the-java-9-module-system/

I have tried opening all required modules some time ago and it did work for me with earlier JDK9 version, but I ended up never using those options.
