### ISSUE TITLE
WebDateField.setDate() does not update selection of calendar.

### ISSUE THREAD

**Issue by htetaungkhant** [mgarin/weblaf#511]

**Comment by mgarin** [comment]
What WebLaF version are you using?

**Comment by mgarin** [comment]
I'll close this issue for now as this have been fixed quite a while ago and shouldn't appear on newer versions, but feel free to reopen it if it still does appear for you.

**Comment by htetaungkhant** [comment]
I am using WebLaF v1.29 [pre-release] and jdk1.8.0_65 and still not change the selection of webCalendar.

**Comment by mgarin** [comment]
Can you try running the `styling` branch snapshot?

You can find it's builds here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

Or you can add it to your Maven project (if you are using one) like this:
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-demo</artifactId>
            <version>1.2.9-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

This is version is most recent and it will be released today with some changes coming soon. There should be no calendar selection issues in it.

**Comment by htetaungkhant** [comment]
Ok,I think I should tell you more detail.
I already used weblaf-complete-1.29.jar (Core module + UI module + dependencies) in my eclipse java project. And I created WebDateField with these java code. And I also created JButton. When I click this JButton,I want to reset datePicker. This is my example code....
WebDateField datePicker=new WebDateField(new Date());
JButton jbtReset=WebButton.createIconWebButton (refreshImage, StyleConstants.smallRound, true ) ;
		jbtReset.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
					datePicker.setDate(new Date());
			}
		});

**Comment by mgarin** [comment]
You are certainly using an older version (v1.29) - the one I mentioned above (v1.2.9) is different. I can tell that because `WebButton.createIconWebButton()` method have been gone for a long time.

The versioning changed so it is confusing, but you might want to try the version from the link I provided - it is dramatically different.

I tried the example you provided with slight modifications for newer version:
```java
import com.alee.extended.date.WebDateField;
import com.alee.extended.window.TestFrame;
import com.alee.laf.WebLookAndFeel;
import com.alee.laf.button.WebButton;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

/**
 * @author Mikle Garin
 */
public class DateFieldTest
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            public void run ()
            {
                WebLookAndFeel.install ();

                final WebDateField datePicker = new WebDateField ( new Date () );

                final JButton jbtReset = new WebButton ( "reset" );
                jbtReset.addActionListener ( new ActionListener ()
                {
                    public void actionPerformed ( final ActionEvent e )
                    {
                        datePicker.setDate ( new Date () );
                    }
                } );

                TestFrame.show ( true, datePicker, jbtReset );
            }
        } );
    }
}
```
And it does work correctly in the cases you have described.

**Comment by mgarin** [comment]
Just to make it a bit more clear - 
Version provided on the site is v1.29 - it is an old pre-release build based on `master` branch code
Version that is the newest one is v1.2.9 - it is a `styling` branch code snapshot build

Those versions are completely different. I know it is confusing but I am wrapping up with 1.2.9 development right now and things will become clear once it is out. And I will make sure to replace all dated builds with recent ones.

**Comment by htetaungkhant** [comment]
I know that v1.29 and v1.2.9 is different.But where can I download v1.2.9.jar file?

**Comment by mgarin** [comment]
There is no more unified file, at least until release.

You will need two modules - `ui` and `core` from here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

And dependencies from here:
https://github.com/mgarin/weblaf/tree/styling/lib

Add them to project and everything should work.

**Comment by htetaungkhant** [comment]
I want to add just one jar file to my project.Pls

**Comment by mgarin** [comment]
Unfortunately dependencies will be coming separately starting from v1.2.9 as is a quite bad practice to include them into the library JAR itself. 

There might be a single WebLaF JAR as one of the options in the future (unifying `core`, `ui` and other base modules), but it still won't include 3rd party dependencies.

If you don't want to manage dependencies manually in your project - you might want to look towards using Maven, Gradle or any other tool to automate that part. Any of those tools will surely save you a lot of time once you get used to it.

**Comment by mgarin** [comment]
Also from the 3rd-party dependencies you only really need:
- java-image-scaling-0.8.6.jar
- jericho-html-3.3.jar
- rsyntaxtextarea-2.6.0.jar
- slf4j-api-1.7.25.jar
- svg-salamander-1.0.jar
- xstream-1.4.9.jar

These ones are only needed for build/demo:
- junit-4.12.jar
- hamcrest-core-1.3.jar
- slf4j-simple-1.7.25.jar

And `slf4j-api-1.7.25.jar` is simply an API library used to output logs - you can use any of it's implementations (or none) that can be found on their site https://www.slf4j.org, any 3rd-party implementation or even your own one.

**Comment by htetaungkhant** [comment]
I don't know how to use Gradle or Maven to combile many jar files into one.

**Comment by mgarin** [comment]
You wouldn't use it to combine multiple JAR files into one, you would use it to automatically resolve dependencies for your project so you don't need to manually manage them. You can look up any guide on the net (there are plenty of good ones) if you have time and willing to research in that direction.

**Comment by htetaungkhant** [comment]
Ty sir,
you mean Gradle or Maven is not combiling tool.But I want only one jar file.
If you can,pls give me only one jar file(combiling of these jar files).If you can't,I will use these many jar files to my project.

**Comment by mgarin** [comment]
Unfortunately I can't, some of the current dependencies are signed and will simply break if you attempt to combine them into one JAR.  There were some workarounds for that in earlier versions, but those are no more. So yes, it is a hard limitation now and you will have to use separate JAR files.

**Comment by mgarin** [comment]
I'll close this issue now since the initial problem should be resolved in the 1.2.9.

**Comment by htetaungkhant** [comment]
Thanks sir.
Whatever,my problem is solved by v1.2.9.
But I really sad for using these separated jar files.
