### ISSUE TITLE
CheckBox rendering with oxbow library

### ISSUE THREAD

**Issue by mvrozanti** [mgarin/weblaf#512]
Hey there

I'm trying to have weblaf and oxbow coexist within the same project. [This section](https://github.com/eugener/oxbow/wiki/Table-Filtering) of their wiki shows An example filter that can be "applied" to an existing table. It enables the user to filter the JTable such as in MS-Excel.

When I install WebLAF, however, the checkboxes turn "invisible" but the functionality is all there. 
I'm gonna take a wild guess and say this is related to UIManager keys once again.

Is there a quick fix to this? 

Thanks!

**Comment by mgarin** [comment]
Looking at the screenshots - it seems that checkboxes are being rendered in a custom `JList` in the popup. That was a problem with older WebLaF versions but was fixed due to checkbox animations removal in `styling` branch from default checkbox style.

To fix this in the older library version - you can try disabling checkbox animations by changing this flag:
```java
WebCheckBoxStyle.animated = false;
```
Make sure to set this setting before initializing L&F.

**Comment by mvrozanti** [comment]
Still no luck. I'm gonna try using the `styling` branch and report back in a few hours

**Comment by mgarin** [comment]
For older version it's a 50/50 solution and unfortunately the only one that might help without changing any WebLaF source code.

**Comment by mgarin** [comment]
Did the `styling` version help?

**Comment by mvrozanti** [comment]
Sorry for the late response! I actually haven't tried it yet as some other stuff came up at work, where I'm using weblaf. But it's on the list and about to be tested.

**Comment by mgarin** [comment]
Sure, no problem.
